services:
    api:
        build: .
        ports:
            - "8000:8000"
        volumes:
            -  ./backend/tracks:/app/backend/tracks
        environment:
            - PYTHONUNBUFFERED=1
        # volumes:
        #    - ./backend:/app/backend
        # command: uvicorn backend.app.asgi:app --host 0.0.0.0 --port 8000 --reload